Feature: Allow right-side blocks drawer to be extended by default #169
moodle-an-hochschulen/moodle-theme_boost_union pull request #230
Opened 2023-02-23 09:43 UTC by ShUl0w

This PR adds the following functionality to boost_union:
- Added section "Right-hand block drawer" to "Feel -> Blocks" admin settings
- Added functionality: configure right-hand block drawer to be shown on the frontpage without being logged in
- Added functionality: configure right-hand block drawer to be shown on a users first login
- Added functionality: configure right-hand block drawer to be shown for guest users

All changes to the right-hand block drawer behaviour do not impact the state management for users who have interacted with the open/closed state.

2023-03-19 07:30 UTC, abias requested changes
Hi @ShUl0w and @matthias-buttgereit ,

many thanks for working on this issue and for submitting a patch for this feature!

I would love to review your PR now, but I am struggling based on the given structure of this PR:

* May I ask you to rebase your feature branch onto the latest master branch and squash all commits into one commit. Having multiple commits in a PR isn't a real problem as we can squash them into one commit during integration at the latest. However, you also have this [Merge remote-tracking branch](https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/pull/230/commits/3e4bceca3c7f0eeed93cb3386dbbf13317a14e50) commit in your feature branch's history. This means that your commits are interweaved with the master commits which makes rebasing onto latest master during the peer review a pain. If you ever want to update a pending feature branch onto laster master, please use a normal `git rebase` to ease the integrator's life :)
* I have spotted that you fixed two whitespace glitches in CHANGES.md and README.md on-the-fly. These are not related to this feature. I am grateful for this finding and have just fixed it in master in https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/commit/d6cfd6a0815ec1b5e338ce53a5d7f9a23ddd7739. As soon as you rebase your branch, these changes will not be a part of your PR anymore.
* I have added two small comments which you could already solve during your rebase work.

Thanks again for your support.
I will have a look at the rest of the code and the feature as soon as the PR is rebased.

Cheers,
Alex

2023-03-19 07:30 UTC, abias commented on CHANGES.md
> +* 2023-02-23 - Feature: Allow right-side blocks drawer to be extended by default #169.
```suggestion
### Unreleased

* 2023-02-23 - Feature: Allow right-side blocks drawer to be extended by default #169.

### v4.1-r2
```

This is not completely obvious and documented in our wiki yet, but you should not add new features under headings of published releases.

2023-03-19 07:30 UTC, abias commented on settings.php
> -
Please leave this second empty line in the file untouched. Having bigger spaces helps to keep the overview of all the settings pages and tabs in this huge settings.php file

2023-04-11 09:35 UTC, ShUl0w commented
Hi @abias ,

thanks a lot for your helpful input and suggestions! Hopefully we have fixed everything as requested. Sorry it took us so long.

2023-04-11 14:08 UTC, lucaboesch commented
Dear @ShUl0w 
I'd like to review your contribution and let me show you what I noted down.

> Dear Tim
> 
> Thanks for your contribution.
> I did play around with it. Despite having all three settings set to "yes" it seems to me it does not have the desired effect.
> In a course with the Search forum block in the block drawer, I enrolled several user that had not accessed before.
> When logging in as them, the block region wasn't extended. I did purge cache
> 
> The drawer class opening tag says
> `<div class="drawer drawer-right d-print-none" data-region="fixed-drawer" id="theme_boost-drawers-blocks" data-preference="drawer-open-block" data-state="show-drawer-right" data-forceopen="" data-close-on-resize="1" aria-hidden="true">`
> 

Then I realized where I went wrong. Hang on, this setting only affects site home!
There is nothing bad with this, only that I think this should be distinguished more clearly. In the future settings and functionality may come up which deal with this on course level, on dashboard level or on "my courses" level.
It would be great if you could address this, in the settings' titles but also in the Issue and in the README and CHANGES ("Allow right-side blocks drawer to be extended by default" is just to generic and leads to things like my misunderstanding).

Regarding the settings texts, please instead of writing "With this setting on 'yes' …", please stick to the "With this setting, …" as the other of the Boost Campus settings. 'yes' and 'no' as options are self-explaining as settings values, aren't they?

Then, your IDE (I suppose you didn't do that on purpose yourself) fiddled around with alignment, empty space and so on. That is hardly desirable. Could you please assure that lines which you didn't actively touch and modify stay unchanged to minimize the diff (in our case it even makes automated tests fail because of end-of-the-line whitespace)?

That would be great.

If you could address all this, I'm sure your contribution can be merged soon.

Best,
Luca

2023-04-11 14:46 UTC, ShUl0w commented
Hi @lucaboesch,

I absolutely understand the confusion, as - ironically - we ourselves experienced it when writing the Behat tests for this feature. The issue with this actually boils down to Moodle 4.x treating those drawers as different entities. Therefore I would also suggest opening another feature for this, as the workload differs a bit from what has been accomplished in this feature.

I will fix the other mentioned issues asap. Regarding the linting: may I suggest adding linting configs (or guidelines) to the plugin in the near future? This would be immensely helpful when working on a feature with multiple devs at once, or handling larger merge conflicts.

2023-04-11 14:56 UTC, lucaboesch commented
I think, @ShUl0w, we do adhere to the general Moodle Coding guidelines, the ones the Moodle Plugin CI checks against.
Is that enough? Otherwise the Coding standards are explained here: https://moodledev.io/general/development/policies/codingstyle. But there's room for space and tolerance: @abias and I do concatenate strings differently, I like to put spaces before and after a dot to 'con' . 'catenate' when Alex prefer to write it 'to'.'gether'.

😀

Oh, I did forget something before: you might as well adopt the date of the fix in CHANGES.md.

Best,
Luca

2023-04-13 09:11 UTC, lucaboesch approved these changes
Dear @abias and @ShUl0w I do approve of this change, furthermore I think there is a case for the brackets around the link in CHANGES.md.

So, yes, please merge.

Best,
Luca

2023-04-13 09:12 UTC, merged

2023-05-09 16:55 UTC, mwilday commented
Another location that would be great to force open on the first visit is Course Home pages. 

On another note, I'm not sure if I should comment here or create a new issue/request... but it would also be great if users could force open the block drawer on specific pages like Home, Dashboard, Site Administration, My Courses, Course Home pages, etc. We envision this as a list of "types of pages" with a checkbox to force the drawer on those pages open. 

In our case, we have defaulted to the My Dashboard page on login and are pushing site news announcements to the dashboard page. We manually adjusted the CSS to keep the drawer open. Still, I see the usefulness of having this be a setting within Boost Campus to allow admins to force the drawer open and remove the toggle feature from specific pages where it might benefit the user to see the sidebar content. 

Here's the CSS we're using to force it open on the My Dashboard page on small screen mobile devices... 
`/***Makes block area perseistent on non-mobile devices***/
@media screen and (min-width: 768px) {
	#page-my-index .drawer.drawer-right{
		right:0;
		visibility: visible;
		position: absolute;
		z-index: 1;
		position: fixed;
		margin-top: 0;
	}

	#page-my-index #page{
		margin-right: 315px;
	}
	#page-my-index .drawerheader,
	#page-my-index .drawer-right-toggle {
		display: none;
	}
}
`