Move back to top button when right drawer is shown
moodle-an-hochschulen/moodle-theme_boost_union pull request #48
Opened 2022-07-08 08:24 UTC by yanus

Currently the "Back to top" button floats over the right drawer when it is shown (see screenshot).
This pull request moves it over the main content to line up with the floating footer button.

![image](https://user-images.githubusercontent.com/5475686/177949978-5dd906e8-5298-4b31-a08f-b889e53feae3.png)

2022-07-08 08:31 UTC, lucaboesch commented
@abias maybe you could peer review this?

2022-07-08 10:22 UTC, abias requested changes
Hi @yanus ,

thank you very much for your PR!

It's a shame that I missed that detail myself when I built the back-to-top button.

I had a look at your patch and while it worked smoothly in the browser, I have two change requests regarding the implementation.

As soon as I had the change to fix this, this is ready to be merged.

Cheers,
Alex

2022-07-08 10:22 UTC, abias commented on scss/boost_union/post.scss
> +    right: calc(315px + 2rem);
Looking at the place where Moodle core sets this style for the footer button on https://github.com/moodle/moodle/blob/master/theme/boost/scss/moodle/layout.scss#L212-L214, you will see that these 315px come from a SCSS variable.

So, this line should say:

```suggestion
    right: calc(#{$drawer-right-width} + 2rem);
```

PS: It's not necessary to add the .jsenabled class as well as the back-to-top button is not shown at all without JS enabled.

2022-07-08 10:22 UTC, abias commented on scss/boost_union/post.scss
> +    transition: right 0.2s;
Looking at the place where Moodle core sets this style for the footer button on https://github.com/moodle/moodle/blob/master/theme/boost/scss/moodle/layout.scss#L199, you will see that the transition is built with a SCSS include.

So, I think this line should say:

```suggestion
    @include transition(0.2s);
```

2022-07-08 10:37 UTC, abias commented
On another note, we are currently discussing the way how to add contributors to the plugin documentation in https://github.com/moodle-an-hochschulen/moodle-theme_boost_union/issues/44.

If you want to be mentioned there are code contributor, please tell us your organization / employer (if there is any) and we will add you accordingly.

2022-07-13 05:49 UTC, abias commented
Hi @yanus ,

as you allowed the peer reviewer to push to your repo, I just went ahead and applied the small changes to the branch in your repo and will now merge the PR.

Thanks again for your contribution!

2022-07-13 05:49 UTC, abias approved these changes

2022-07-13 05:50 UTC, merged